name: Test Workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  


test: 

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t coderbot -f flask.Dockerfile
      - name: Tags
        run: |
          docker tag coderbot ${{ secrets.DOCKER_USER }}/coderbot:${{ github.sha }}
          docker tag coderbot ${{ secrets.DOCKER_USER }}/coderbot:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/coderbot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/coderbot:latest  
      - name: Test with pytest in Docker Container # Will need to Adjust later to add Heroku for testing
        run: |
          pytest -v test/test_api.py
